# # This script rescales the data for each dictionary gathered from the "urgency" survey.

# # Note that the coefficients and standard errors in the data refer to the
# # coefficients generated by the Bradley-Terry models for pairwise comparisons.
# # The assigned scores are author assigned scores before survey.
# # These served as controls in models to account for "expected outcomes" and
# # improve the coefficient ranks (i.e. odds of winning in pairwise comparison).

# # The first task is to get close synonyms or versions of adjective/adverbs
# # scored in the same ways.
# # This is done since not all versions of the same word were surveyed.
# # The second tasks refers to how the scores are rescaled to calculate urgency
# # and the urgency of priorities.
# # Scaled variables refer to scaled coefficients.
# # Scaling is done using 1-coefficient/min(coefficient) scaled from 0.05 to 1.
# # Rescaled variables refer to centered coefficients (around a neutral term)
# # and then scaled.
# # Rescaling is done using 1+centered coefficient/min(centered coefficient).
# # This is only done for timing, frequency, and intensity since rescaled scores
# # are meant to be used to calculate the urgency of priorities only.

library(readr)
library(dplyr)
library(scales)

# # Timing dictionary

# Load original data
timing <- read_csv("data_raw/time.csv")

# Standardise scores for synonyms/equivalents
timing[which(timing$word=="hasty"),3] <- timing[which(timing$word=="hastily"),3]
timing[which(timing$word=="immediate"),3] <- timing[which(timing$word=="immediately"),3]
timing[which(timing$word=="imminent"),3] <- timing[which(timing$word=="imminently"),3]
timing[which(timing$word=="prompt"),3] <- timing[which(timing$word=="promptly"),3]
timing[which(timing$word=="quick"),3] <- timing[which(timing$word=="quickly"),3]
timing[which(timing$word=="speedy"),3] <- timing[which(timing$word=="speedily"),3]
timing[which(timing$word=="short"),3] <- timing[which(timing$word=="shortly"),3]
timing[which(timing$word=="earlier"),3] <- timing[which(timing$word=="early"),3]
timing[which(timing$word=="rapid"),3] <- timing[which(timing$word=="rapidly"),3]
timing[which(timing$word=="late"),3] <- timing[which(timing$word=="later"),3]
timing[which(timing$word=="slow"),3] <- timing[which(timing$word=="slowly"),3]

# Rescale coefficients
timing[timing$word=="afterwards",3] # centering word score = 4.19
timing <- timing %>%
  mutate(centered_coefficient = coefficient + 4.19,
         scaled = scales::rescale(1-(coefficient/min(timing$coefficient, na.rm = TRUE)), to = c(0.05, 1)),
         rescaled = ifelse(grammar_function != "adjective",
                           1+(centered_coefficient/max(timing$centered_coefficient, na.rm = TRUE)), NA))


# # Commitment dictionary

# Get original file
commitment <- read_csv("data_raw/comm.csv")

# Standardise scores for synonyms/equivalents
commitment[which(commitment$word=="necessarily"),3] <- commitment[which(commitment$word=="necessary"),3]
commitment[which(commitment$word=="importantly"),3] <- commitment[which(commitment$word=="important"),3]
commitment[which(commitment$word=="obligatory"),3] <- commitment[which(commitment$word=="oblige to"),3]
commitment[which(commitment$word=="require to"),3] <- commitment[which(commitment$word=="need to"),3]
commitment[which(commitment$word=="commit to"),3] <- commitment[which(commitment$word=="promise to"),3]
commitment[which(commitment$word=="intend to"),3] <- commitment[which(commitment$word=="promise to"),3]
commitment[which(commitment$word=="urge to"),3] <- commitment[which(commitment$word=="going to"),3]
commitment[which(commitment$word=="relevantly"),3] <- commitment[which(commitment$word=="relevant"),3]
commitment[which(commitment$word=="eminent"),3] <- commitment[which(commitment$word=="important"),3]
commitment[which(commitment$word=="prominent"),3] <- commitment[which(commitment$word=="important"),3]
commitment[which(commitment$word=="prominently"),3] <- commitment[which(commitment$word=="important"),3]
commitment[which(commitment$word=="preeminent"),3] <- commitment[which(commitment$word=="important"),3]
commitment[which(commitment$word=="pre-eminent"),3] <- commitment[which(commitment$word=="important"),3]
commitment[which(commitment$word=="momentous"),3] <- commitment[which(commitment$word=="important"),3]
commitment[which(commitment$word=="worthy"),3] <- commitment[which(commitment$word=="invaluable"),3]
commitment[which(commitment$word=="quintessential"),3] <- commitment[which(commitment$word=="essential"),3]
commitment[which(commitment$word=="valuable"),3] <- commitment[which(commitment$word=="invaluable"),3]
commitment[which(commitment$word=="unavoidably"),3] <- commitment[which(commitment$word=="unavoidable"),3]
commitment[which(commitment$word=="inevitable"),3] <- commitment[which(commitment$word=="unavoidable"),3]
commitment[which(commitment$word=="inevitably"),3] <- commitment[which(commitment$word=="unavoidable"),3]
commitment[which(commitment$word=="inexorable"),3] <- commitment[which(commitment$word=="unavoidable"),3]
commitment[which(commitment$word=="inexorably"),3] <- commitment[which(commitment$word=="unavoidable"),3]
commitment[which(commitment$word=="let us"),3] <- commitment[which(commitment$word=="let's"),3]
commitment[which(commitment$word=="shall"),3] <- commitment[which(commitment$word=="should"),3]
commitment[which(commitment$word=="plan to"),3] <- commitment[which(commitment$word=="intend to"),3]
commitment[which(commitment$word=="marginal"),3] <- commitment[which(commitment$word=="optional"),3]
commitment[which(commitment$word=="tenable"),3] <- commitment[which(commitment$word=="able"),3]
commitment[which(commitment$word=="doable"),3] <- commitment[which(commitment$word=="able"),3]
commitment[which(commitment$word=="plausible"),3] <- commitment[which(commitment$word=="possible"),3]
commitment[which(commitment$word=="plausibly"),3] <- commitment[which(commitment$word=="possible"),3]
commitment[which(commitment$word=="possibly"),3] <- commitment[which(commitment$word=="possible"),3]
commitment[which(commitment$word=="useable"),3] <- commitment[which(commitment$word=="useful"),3]
commitment[which(commitment$word=="ideally"),3] <- commitment[which(commitment$word=="ideal"),3]
commitment[which(commitment$word=="careful"),3] <- commitment[which(commitment$word=="cautious"),3]
commitment[which(commitment$word=="carefully"),3] <- commitment[which(commitment$word=="cautious"),3]
commitment[which(commitment$word=="obvious"),3] <- commitment[which(commitment$word=="able"),3]
commitment[which(commitment$word=="vague"),3] <- commitment[which(commitment$word=="ambiguous"),3]
commitment[which(commitment$word=="option to"),3] <- commitment[which(commitment$word=="optional"),3]
commitment[which(commitment$word=="preferably"),3] <- commitment[which(commitment$word=="preferable"),3]
commitment[which(commitment$word=="get to"),3] <- commitment[which(commitment$word=="going to"),3]

# Save/Move "commitment" adverbs to intensity as they are intensifiers
comm_adv <- filter(commitment, grammar_function == "adverb") # separate adverbs

# Rescale coefficients
commitment <- filter(commitment, grammar_function != "adverb") %>%
  mutate(scaled = scales::rescale(1-(coefficient/min(commitment$coefficient, na.rm = TRUE)), to = c(0.05, 1)),
         rescaled = scales::rescale(ifelse(grammar_function != "adjective",
                                           1-(coefficient/min(commitment$coefficient, na.rm = TRUE)),
                                           NA), to = c(0.05, 1)))

# # Intensity dictionary

# Load original data
intensity <- read_csv("data_raw/int.csv")

# Standardise synonyms/equivalents
intensity[which(intensity$word=="deeply"),3] <- intensity[which(intensity$word=="extremely"),3] # add scale values for similar words
intensity[which(intensity$word=="high"),3] <- intensity[which(intensity$word=="highly"),3]
intensity[which(intensity$word=="definite"),3] <- intensity[which(intensity$word=="definitely"),3]
intensity[which(intensity$word=="surely"),3] <- intensity[which(intensity$word=="certainly"),3]
intensity[which(intensity$word=="certain"),3] <- intensity[which(intensity$word=="certainly"),3]
intensity[which(intensity$word=="utterly"),3] <- intensity[which(intensity$word=="completely"),3]
intensity[which(intensity$word=="absolutely"),3] <- intensity[which(intensity$word=="completely"),3]
intensity[which(intensity$word=="urgent"),3] <- intensity[which(intensity$word=="urgently"),3]
intensity[which(intensity$word=="vigorously"),3] <- intensity[which(intensity$word=="strongly"),3]
intensity[which(intensity$word=="vigorous"),3] <- intensity[which(intensity$word=="strongly"),3]
intensity[which(intensity$word=="huge"),3] <- intensity[which(intensity$word=="enormous"),3]
intensity[which(intensity$word=="large"),3] <- intensity[which(intensity$word=="enormous"),3]
intensity[which(intensity$word=="largest"),3] <- intensity[which(intensity$word=="enormous"),3]
intensity[which(intensity$word=="big"),3] <- intensity[which(intensity$word=="enormous"),3]
intensity[which(intensity$word=="biggest"),3] <- intensity[which(intensity$word=="enormous"),3]
intensity[which(intensity$word=="global"),3] <- intensity[which(intensity$word=="everywhere"),3]
intensity[which(intensity$word=="globally"),3] <- intensity[which(intensity$word=="everywhere"),3]
intensity[which(intensity$word=="prevalent"),3] <- intensity[which(intensity$word=="pervasive"),3]
intensity[which(intensity$word=="extensively"),3] <- intensity[which(intensity$word=="extensive"),3]
intensity[which(intensity$word=="tremendous"),3] <- intensity[which(intensity$word=="enormous"),3]
intensity[which(intensity$word=="extraordinary"),3] <- intensity[which(intensity$word=="exceptional"),3]
intensity[which(intensity$word=="remarkably"),3] <- intensity[which(intensity$word=="remarkable"),3]
intensity[which(intensity$word=="immense"),3] <- intensity[which(intensity$word=="enormous"),3]
intensity[which(intensity$word=="vast"),3] <- intensity[which(intensity$word=="enormous"),3]
intensity[which(intensity$word=="ultimate"),3] <- intensity[which(intensity$word=="enormous"),3]
intensity[which(intensity$word=="ambitiously"),3] <- intensity[which(intensity$word=="determined"),3]
intensity[which(intensity$word=="ambitious"),3] <- intensity[which(intensity$word=="determined"),3]
intensity[which(intensity$word=="realistically"),3] <- intensity[which(intensity$word=="realistic"),3]
intensity[which(intensity$word=="more"),3] <- intensity[which(intensity$word=="moderately"),3]
intensity[which(intensity$word=="moderate"),3] <- intensity[which(intensity$word=="moderately"),3]
intensity[which(intensity$word=="substantial"),3] <- intensity[which(intensity$word=="substantially"),3]
intensity[which(intensity$word=="lots"),3] <- intensity[which(intensity$word=="substantially"),3]
intensity[which(intensity$word=="plenty"),3] <- intensity[which(intensity$word=="substantially"),3]
intensity[which(intensity$word=="much"),3] <- intensity[which(intensity$word=="substantially"),3]
intensity[which(intensity$word=="totally"),3] <- intensity[which(intensity$word=="fully"),3]
intensity[which(intensity$word=="entirely"),3] <- intensity[which(intensity$word=="fully"),3]
intensity[which(intensity$word=="far"),3] <- intensity[which(intensity$word=="substantially"),3]
intensity[which(intensity$word=="clearly"),3] <- intensity[which(intensity$word=="clear"),3]
intensity[which(intensity$word=="least"),3] <- intensity[which(intensity$word=="almost"),3]
intensity[which(intensity$word=="less"),3] <- intensity[which(intensity$word=="almost"),3]
intensity[which(intensity$word=="small"),3] <- intensity[which(intensity$word=="limited"),3]
intensity[which(intensity$word=="marginally"),3] <- intensity[which(intensity$word=="limited"),3]
intensity[which(intensity$word=="minimum"),3] <- intensity[which(intensity$word=="minimal"),3]
intensity[which(intensity$word=="weakly"),3] <- intensity[which(intensity$word=="slightly"),3]
intensity[which(intensity$word=="adequate"),3] <- intensity[which(intensity$word=="adequately"),3]
intensity[which(intensity$word=="sufficient"),3] <- intensity[which(intensity$word=="enough"),3]
intensity[which(intensity$word=="near"),3] <- intensity[which(intensity$word=="nearly"),3]
intensity[which(intensity$word=="some"),3] <- intensity[which(intensity$word=="modest"),3]
intensity[which(intensity$word=="slight"),3] <- intensity[which(intensity$word=="slightly"),3]
intensity[which(intensity$word=="reasonable"),3] <- intensity[which(intensity$word=="reasonably"),3]
intensity[which(intensity$word=="wide"),3] <- intensity[which(intensity$word=="extensive"),3]
intensity[which(intensity$word=="widely"),3] <- intensity[which(intensity$word=="extensive"),3]
intensity[which(intensity$word=="widespread"),3] <- intensity[which(intensity$word=="extensive"),3]
intensity[which(intensity$word=="intensive"),3] <- intensity[which(intensity$word=="intense"),3]
intensity[which(intensity$word=="intensely"),3] <- intensity[which(intensity$word=="intense"),3]

# Merge commitment adverbs and rescale coefficients
intensity[intensity$word=="simply",3] # centering word score = 0.75
intensity <- full_join(intensity, comm_adv) %>%
  mutate(centered_coefficient = coefficient + 0.75,
         scaled = scales::rescale(1-(coefficient/min(intensity$coefficient, na.rm = TRUE)), to = c(0.05, 1)),
         rescaled = ifelse(grammar_function != "adjective",
                           1+(centered_coefficient/max(intensity$centered_coefficient, na.rm = TRUE)), NA))

# # Frequency dictionary

# Load original data
frequency <- read_csv("data_raw/freq.csv")

# Persistently is a big outlier, so we will remove it for now
#frequency[which(frequency$word=="persistently"),3] <- NA
# # (another option would be to take the score from another term)
frequency[which(frequency$word=="persistently"),4] <-
  frequency[which(frequency$word=="relentlessly"),4]

# Standardise scores for synonyms/equivalents
frequency[which(frequency$word=="frequent"),3] <- frequency[which(frequency$word=="frequently"),3]
frequency[which(frequency$word=="constant"),3] <- frequency[which(frequency$word=="constantly"),3]
frequency[which(frequency$word=="by the minute"),3] <- frequency[which(frequency$word=="hourly"),3]
frequency[which(frequency$word=="by the hour"),3] <- frequency[which(frequency$word=="hourly"),3]
frequency[which(frequency$word=="everyday"),3] <- frequency[which(frequency$word=="daily"),3]
frequency[which(frequency$word=="nightly"),3] <- frequency[which(frequency$word=="daily"),3]
frequency[which(frequency$word=="every night"),3] <- frequency[which(frequency$word=="daily"),3]
frequency[which(frequency$word=="persistent"),3] <- frequency[which(frequency$word=="persistently"),3]
frequency[which(frequency$word=="relentless"),3] <- frequency[which(frequency$word=="relentlessly"),3]
frequency[which(frequency$word=="incessant"),3] <- frequency[which(frequency$word=="incessantly"),3]
frequency[which(frequency$word=="unrelentingly"),3] <- frequency[which(frequency$word=="relentlessly"),3]
frequency[which(frequency$word=="interminable"),3] <- frequency[which(frequency$word=="incessantly"),3]
frequency[which(frequency$word=="interminably"),3] <- frequency[which(frequency$word=="incessantly"),3]
frequency[which(frequency$word=="fortnightly"),3] <- frequency[which(frequency$word=="weekly"),3]
frequency[which(frequency$word=="yearly"),3] <- frequency[which(frequency$word=="annually"),3]
frequency[which(frequency$word=="every year"),3] <- frequency[which(frequency$word=="annually"),3]
frequency[which(frequency$word=="every hour"),3] <- frequency[which(frequency$word=="hourly"),3]
frequency[which(frequency$word=="every minute"),3] <- frequency[which(frequency$word=="hourly"),3]
frequency[which(frequency$word=="every week"),3] <- frequency[which(frequency$word=="weekly"),3]
frequency[which(frequency$word=="every month"),3] <- frequency[which(frequency$word=="monthly"),3]
frequency[which(frequency$word=="normally"),3] <- frequency[which(frequency$word=="usually"),3]
frequency[which(frequency$word=="regular"),3] <- frequency[which(frequency$word=="regularly"),3]
frequency[which(frequency$word=="steady"),3] <- frequency[which(frequency$word=="steadily"),3]
frequency[which(frequency$word=="infrequent"),3] <- frequency[which(frequency$word=="infrequently"),3]
frequency[which(frequency$word=="progressive"),3] <- frequency[which(frequency$word=="progressively"),3]
frequency[which(frequency$word=="gradual"),3] <- frequency[which(frequency$word=="gradually"),3]
frequency[which(frequency$word=="occasional"),3] <- frequency[which(frequency$word=="infrequently"),3]
frequency[which(frequency$word=="occasionally"),3] <- frequency[which(frequency$word=="infrequently"),3]
frequency[which(frequency$word=="sporadic"),3] <- frequency[which(frequency$word=="sporadically"),3]
frequency[which(frequency$word=="irregular"),3] <- frequency[which(frequency$word=="irregularly"),3]
frequency[which(frequency$word=="intermittent"),3] <- frequency[which(frequency$word=="intermittently"),3]
frequency[which(frequency$word=="rare"),3] <- frequency[which(frequency$word=="rarely"),3]

# Rescale coefficients
(unlist(frequency[frequency$word=="gradual",3]) + # between gradual and usually
    unlist(frequency[frequency$word=="usually",3]))/2 # centering word score = 4.51
frequency <- frequency %>%
  mutate(centered_coefficient = coefficient + 4.51,
         scaled = scales::rescale(1-(coefficient/min(frequency$coefficient, na.rm = TRUE)), to = c(0.05, 1)),
         rescaled = ifelse(grammar_function != "adjective",
                           1+(centered_coefficient/max(frequency$centered_coefficient, na.rm = TRUE)), NA))

# # Save the data as internal data
# # Note that the CAP Topics is another type of internal data saved in package
# # that should be (re)saved as well.
# usethis::use_data(CAP_topics, commitment, frequency, intensity, timing,
#                   internal = TRUE, overwrite = TRUE)
