---
title: "COP 21 - Leaders' Statements"
author: "Henrique Sposito"
date: "2024-05-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(poldis)
library(readxl)
library(dplyr)
library(ggplot2)
library(messydates)
```

```{r}
Paris_leader_statements <- 
  read_excel("Paris-leader-statements.xlsx") |>
  select(Country, Speaker, 'Text EN') |>
  na.omit()
sentences <- annotate_text(Paris_leader_statements$`Text EN`,
                           level = "sentences")
promises <- extract_promises(sentences)
subjects <- extract_subjects(promises)
related_terms <- extract_related_terms(promises, subjects = c("climate",
                                                              "poverty",
                                                              "development"))
urgency <- get_urgency(promises, related_terms)
get_urgency_rank(urgency)
```


```{r}
load("US_Oral_Remarks.rda")
US_Oral_Remarks_CC <- US_Oral_Remarks |>
  filter(grepl("climate change|global warming", text)) |>
  mutate(id = paste0("text", row_number()),
         year = stringr::str_extract(date, "[:digit:]{4}"))
sentences <- annotate_text(US_Oral_Remarks_CC$text,
                           level = "sentences")
promises <- extract_promises(sentences)
subjects <- extract_subjects(promises)
related_terms <- extract_related_terms(promises, subjects = c("climate",
                                                              "poverty",
                                                              "development"))
urgency <- get_urgency(promises, related_terms)
get_urgency_rank(urgency)
urgency_text <- urgency |> 
  group_by(doc_id) |> 
  summarize(m_urgency = mean(urgency), t_urgency = sum(urgency)) |>
  rename(id = doc_id)
US_Oral_Remarks_CC_U <- dplyr::left_join(US_Oral_Remarks_CC, urgency_text)
US_Oral_Remarks_CC_U |>
  ggplot(aes(x = as.numeric(year), y = m_urgency)) + 
  geom_smooth() +
  theme_classic() +
  labs(title = "Urgency in Climate Change related speeches",
       subtitle = "US presidential speeches since 1995",
       x = "Year", y = "Mean Urgency Score")
US_Oral_Remarks_CC_U |>
  filter(speaker == "Barack Obama"|speaker == "Joseph R. Biden") |>
  ggplot(aes(x = as.numeric(year), y = m_urgency)) + 
  geom_smooth(aes(color = speaker), se = FALSE) +
  theme_classic() +
  labs(title = "Urgency in Climate Change related speeches for Biden and Obama",
       subtitle = "US presidential speeches since 2008",
       x = "Year", y = "Mean Urgency Score", color = "")
```

```{r}
library(deeplr)
library(quanteda)
library(patchwork)
# load EU speeches data
load("EUspeech_V2.RData") 
EU_speeches <- convert(corpus, to = "data.frame")
table(EU_speeches$country) # see obs by country
# EU_speeches <- EU_speeches |>
#   filter(country == "Great Britain"|country == "France"|
#            country == "Denmark"|country == "Netherlands",
#          date >= "2010-01-01") |>
#   mutate(translated_text = ifelse(language == "en", text, NA))
# out <- list()
# for(i in seq_len(nrow(EU_speeches))) {
#   out[[i]] <- ifelse(is.na(EU_speeches$translated_text[[i]]),
#                      deeplr::translate2(EU_speeches$text[[i]],
#                                         source_lang = toupper(EU_speeches$language[[i]]),
#                                         auth_key = my_key),
#                      EU_speeches$translated_text[[i]])
# }
UK_speeches <- EU_speeches |> filter(country == "Great Britain",
                                     date >= "2010-01-01",
                                     date <= "2019-12-31") |>
  mutate(year = stringr::str_extract(date, "[:digit:]{4}")) |>
  select(title, speaker, country, year, text)
load("US_Oral_Remarks.rda")
US_Oral_Remarks <- US_Oral_Remarks |>
  mutate(year = stringr::str_extract(date, "[:digit:]{4}"),
         country = "United States") |>
  filter(year >= "2010", year <= "2019") |>
  select(title, speaker, country, year, text)
US_UK_speeches <- rbind(UK_speeches, US_Oral_Remarks) |>
  mutate(id = paste0("text", row_number()))
sentences <- annotate_text(US_UK_speeches$text, level = "sentences")
urgency <- get_urgency(sentences)
urgency_cc <- urgency |> filter(grepl("climate change|global warming",
                                      sentence, ignore.case = TRUE))
urgency_text <- urgency_cc |> 
  group_by(doc_id) |> 
  summarize(m_urgency = mean(urgency), t_urgency = sum(urgency)) |>
  rename(id = doc_id) |>
  left_join(US_UK_speeches)

urgency_text |> group_by(speaker) |> 
  summarize(m_urgency = mean(m_urgency), t_urgency = sum(t_urgency))

p1 <- urgency_text |>
  ggplot(aes(x = as.numeric(year), y = m_urgency)) + 
  geom_smooth(aes(color = country), se = FALSE) +
  theme_classic() +
  labs(x = "Year", y = "Mean Urgency Score", color = "")
p2 <- urgency_text |>
  ggplot(aes(x = as.numeric(year), y = t_urgency)) + 
  geom_smooth(aes(color = country), se = FALSE) +
  theme_classic() +
  labs(x = "Year", y = "Total Urgency Score", color = "")
wrap_plots(p1, p2, guides = "collect") +
  plot_annotation(title = "Urgency in Climate Change promises",
                  subtitle = "US and UK speeches from 2010-2019")
```

```{r}
# urgency vs. sentiment
library(tidytext)
sent_urg <- urgency_cc %>%
  unnest_tokens(word, sentence) %>%
  inner_join(get_sentiments("afinn"), by = "word") %>%
  group_by(doc_id) %>% 
  summarise(m_sentiment = mean(value), t_sentiment = sum(value)) %>% 
  rename(id = doc_id) |>
  left_join(urgency_text)
p3 <- sent_urg |>
  ggplot(aes(x = as.numeric(year))) + 
  geom_smooth(aes(y = m_sentiment, color = country), se = FALSE) +
  theme_classic() +
  labs(x = "Year", y = "Mean Sentiment Score", color = "")
p4 <- sent_urg |>
  ggplot(aes(x = as.numeric(year), y = t_sentiment)) + 
  geom_smooth(aes(color = country), se = FALSE) +
  theme_classic() +
  labs(x = "Year", y = "Total Sentiment Score", color = "")
wrap_plots(p1, p2, p3, p4, guides = "collect") +
  plot_annotation(title = "Urgency vs. Sentiment in Climate Change Related Promises",
                  subtitle = "US presidential and UK prime minister speeches from 2010-2019")
```

```{r}
p5 <- sent_urg |>
  filter(speaker == "Barack Obama" | speaker == "D.Cameron") |>
  ggplot(aes(x = as.numeric(year))) + 
  geom_smooth(aes(y = m_urgency, color = speaker), se = FALSE) +
  theme_classic() +
  labs(x = "Year", y = "Mean Urgency Score", color = "")
p6 <- sent_urg |>
  filter(speaker == "Barack Obama" | speaker == "D.Cameron") |>
  ggplot(aes(x = as.numeric(year))) + 
  geom_smooth(aes(y = m_sentiment, color = speaker), se = FALSE) +
  theme_classic() +
  labs(x = "Year", y = "Mean Sentiment Score", color = "")
wrap_plots(p5, p6, guides = "collect") +
  plot_annotation(title = "Urgency vs. Sentiment in Climate Change Related Promises",
                  subtitle = "Barack Obama vs. David Cameron Speeches 2010-2016")
```

```{r}
library(scales)
sent_urg |>
  filter(speaker == "Barack Obama" | speaker == "D.Cameron") |>
  ggplot(aes(x = as.numeric(year))) + 
  geom_smooth(aes(y = rescale(m_sentiment)), color = "red", se = FALSE) +
  geom_smooth(aes(y = rescale(m_urgency)), color = "blue", se = FALSE)  +              
  theme_classic() +
  annotate("text", x = 2015.8, y = 0.38, label = "Sentiment") +
  annotate("text", x = 2015.8, y = 0.58, label = "Urgency") +
  labs(x = "Year", y = "Mean")
```
