freq_adverbs <- list(
  definite = c("once",
               "twice",
               "annually",
               "daily",
               "fortnightly",
               "hourly",
               "monthly",
               "nightly",
               "quarterly",
               "weekly",
               "yearly"),
  indefinite = c("always",
                 "usually",
                 "often",
                 "sometimes",
                 "rarely",
                 "never",
                 "ever",
                 "hardly ever",
                 "occasionally",
                 "seldom",
                 "generally",
                 "frequently",
                 "normally",
                 "constantly",
                 "infrequently",
                 "regularly")
)

