freq_adverbs <- list(
  definite = c("once",
               "twice",
               "annually",
               "daily",
               "fortnightly",
               "hourly",
               "monthly",
               "nightly",
               "quarterly",
               "weekly",
               "yearly"),
  indefinite = c("always",
                 "usually",
                 "often",
                 "sometimes",
                 "rarely",
                 "never",
                 "ever",
                 "hardly ever",
                 "occasionally",
                 "seldom",
                 "generally",
                 "frequently",
                 "normally",
                 "constantly",
                 "infrequently",
                 "regularly")
)

time_adverbs <- list(
  relative_timepoints = c("yesterday",
                          "then",
                          "now",
                          "today",
                          "tonight",
                          "tomorrow"),
  relational_timepoints = c("already",
                            "daily",
                            "last",
                            "next",
                            "previously",
                            "after",
                            "afterwards",
                            "early",
                            "late",
                            "later",
                            "since",
                            "still",
                            "just",
                            "seldom",
                            "before",
                            "early",
                            "earlier",
                            "eventually",
                            "finally",
                            "first",
                            "formerly",
                            "just",
                            "lately",
                            "recently",
                            "soon",
                            "yet")
)

