# Urgency Analysis

# Dictionaries
freq_adverbs <- list(
  definite = c("once",
               "twice",
               "annually",
               "daily",
               "fortnightly",
               "hourly",
               "monthly",
               "nightly",
               "quarterly",
               "weekly",
               "yearly"),
  indefinite = c("always",
                 "usually",
                 "often",
                 "sometimes",
                 "rarely",
                 "never",
                 "ever",
                 "hardly ever",
                 "occasionally",
                 "seldom",
                 "generally",
                 "frequently",
                 "normally",
                 "constantly",
                 "infrequently",
                 "regularly")
)

time_adverbs <- list(
  relative_timepoints = c("yesterday",
                          "then",
                          "now",
                          "today",
                          "tonight",
                          "tomorrow"),
  relational_timepoints = c("already",
                            "daily",
                            "last",
                            "next",
                            "previously",
                            "after",
                            "afterwards",
                            "early",
                            "late",
                            "later",
                            "since",
                            "still",
                            "just",
                            "seldom",
                            "before",
                            "early",
                            "earlier",
                            "eventually",
                            "finally",
                            "first",
                            "formerly",
                            "just",
                            "lately",
                            "recently",
                            "soon",
                            "yet")
)

degr_adverbs <- c("lots",
                  "somewhat",
                  "barely",
                  "very",
                  "much",
                  "most",
                  "nearly",
                  "too",
                  "extremely",
                  "enough",
                  "so",
                  "slightly",
                  "especially",
                  "just",
                  "almost",
                  "scarcely",
                  "virtually",
                  "fully",
                  "far",
                  "exceptionally",
                  "absolutely",
                  "awfully",
                  "badly",
                  "completely",
                  "decidedly",
                  "deeply",
                  "enormously",
                  "entirely",
                  "fairly",
                  "greatly",
                  "hardly",
                  "highly",
                  "how",
                  "incredibly",
                  "indeed",
                  "intensely",
                  "just",
                  "least",
                  "less",
                  "little",
                  "nearly",
                  "perfectly",
                  "positively",
                  "practically",
                  "pretty",
                  "purely",
                  "quite",
                  "rather",
                  "really",
                  "scarcely",
                  "simply",
                  "strongly",
                  "terribly",
                  "thoroughly",
                  "totally",
                  "utterly",
                  "very",
                  "virtually",
                  "well")
